<script lang="ts">
  import type { Snippet } from "svelte";

  /**
   * The label/control/hint/error shape, in one place.
   *
   * It exists for one rule: the hint and the error are siblings of the <label>,
   * never inside it. A <label> that encloses its hint makes the whole paragraph
   * the control's accessible name — which is why AuthorSection already carries a
   * comment explaining the split, and why RenameDialog keeps its hint outside.
   * Encoding the rule here means nobody has to remember it again.
   *
   * The control arrives as a snippet rather than as markup this file chooses,
   * because the primitives need different elements underneath (input, select in
   * a chevron wrapper, input plus a stepper) but identical wiring on top.
   */
  let {
    id,
    label,
    hint,
    error,
    describedBy,
    labelHidden = false,
    inline = false,
    grow = false,
    control,
  }: {
    /** Generated by the calling primitive with $props.id() and wired to for/id. */
    id: string;
    /** The whole accessible name of the control, and nothing else. */
    label: string;
    hint?: string;
    /** Non-empty means described AND invalid; the control gets aria-invalid. */
    error?: string;
    /** Extra ids to describe with, e.g. a section-level status line. */
    describedBy?: string;
    labelHidden?: boolean;
    /** Label beside the control instead of above it. */
    inline?: boolean;
    grow?: boolean;
    control: Snippet<[{ describedBy: string | undefined; invalid: boolean }]>;
  } = $props();

  let hintId = $derived(hint ? `${id}-hint` : null);
  let errorId = $derived(error ? `${id}-error` : null);

  let described = $derived(
    [describedBy, hintId, errorId].filter((v): v is string => Boolean(v)).join(" ") || undefined,
  );
</script>

<div class="v-field" class:v-field-inline={inline} class:v-field-grow={grow}>
  <label class="v-field-label" class:sr-only={labelHidden} for={id}>{label}</label>

  {@render control({ describedBy: described, invalid: Boolean(error) })}

  {#if hint}<p class="v-field-hint" id={hintId}>{hint}</p>{/if}
  {#if error}<p class="v-field-error" id={errorId} role="alert">{error}</p>{/if}
</div>
