// The comparison's facts, in one place: every cell of the landing's table
// (section IV, #comparar / #compare) and of the full page (/comparar/,
// /en/compare/). The pages are static HTML (compare-build.mjs wrote them from
// this module); compare-parity.mjs holds them to it on every verify.mjs run,
// and sources-live.mjs re-reads the vendors' pages before each re-dating.
//
// A cell is { es, en, s, src, quote? }:
//   s "y"     the vendor's own page or repository says so (src: those pages);
//   s "n"     the vendor's own page says it does NOT: the only way a page may
//             say a competitor lacks something (or needs no account: any
//             "No" about another app). Carries the verbatim quote;
//   s "ns"    not stated on the pages read: renders as a dash, never as "no";
//   s "calc"  our arithmetic from prices the vendor states (`calc` holds it);
//   s "code"  Versorium itself, checked in its code, docs or release.
// `quote` is what the source page says, verbatim (or a fragment of it), so a
// re-read can find it again; prices are USD as the page showed them on AS_OF.
// "three" is the cheapest way to use the app for three years at list price,
// before tax. A standalone "—" inside a cell's text is a part its website
// doesn't state (rendered like a dash cell).
//
// Built 2026-10-04 from the design (~/Documents/Github/.versorium-design/
// versorium-comparison/DESIGN.md), every cell re-read that day in Chrome
// (tests/landing/research/dump-sources.mjs and the other research helpers).

export const AS_OF = "2026-10-04";

const list = (v) => (v == null ? [] : [v].flat());
const y = (es, en, src, quote) => ({ es, en, s: "y", src: list(src), ...(quote ? { quote: list(quote) } : {}) });
const no = (es, en, src, quote) => ({ es, en, s: "n", src: list(src), quote: list(quote) });
const code = (es, en, ...src) => ({ es, en, s: "code", src });
const calc = (es, en, expr, src, quote) => ({ es, en, s: "calc", calc: expr, src: list(src), ...(quote ? { quote: list(quote) } : {}) });
const ns = () => ({ es: null, en: null, s: "ns", src: [] });

/** The pages each fact comes from, all read on AS_OF. `es`/`en` say what the page supports;
    `urlEn`, where there is one, is the same page in English, for the English list. */
export const SOURCES = {
  "vs-readme": { app: "versorium", url: "https://github.com/MAECLY/versorium-app#readme", es: "README: licencia, sin cuenta ni telemetría", en: "README: licence, no account or telemetry" },
  "vs-formats": { app: "versorium", url: "https://github.com/MAECLY/versorium-app/blob/main/FORMATS.md", es: "FORMATS.md: exportar e importar", en: "FORMATS.md: export and import" },
  "vs-todo": { app: "versorium", url: "https://github.com/MAECLY/versorium-app/blob/main/TODO.md", es: "TODO.md: lo que está en la lista", en: "TODO.md: what is on the list" },
  "vs-first": { app: "versorium", url: "https://github.com/MAECLY/versorium-app/releases/tag/v0.1.0", es: "Versión 0.1.0, la primera", en: "Release 0.1.0, the first" },
  // The newest release in the series the landing's note names (compare-parity.mjs warns when a newer one is out).
  "vs-release": { app: "versorium", url: "https://github.com/MAECLY/versorium-app/releases/tag/v0.1.1", es: "Versión 0.1.1, con arreglos", en: "Release 0.1.1, with fixes" },
  "vs-details": { app: "versorium", url: "https://versorium.maecly.com/detalles/", urlEn: "https://versorium.maecly.com/en/details/", es: "Límites y detalles", en: "Limits and details" },

  "scr-store": { app: "scrivener", url: "https://www.literatureandlatte.com/store/scrivener", es: "Tienda: precios por plataforma, iOS y prueba de 30 días", en: "Store: prices per platform, iOS and 30-day trial" },
  "scr-overview": { app: "scrivener", url: "https://www.literatureandlatte.com/scrivener/overview", es: "Funciones: instantáneas, copias, exportar", en: "Features: snapshots, backups, export" },
  "scr-faq": { app: "scrivener", url: "https://www.literatureandlatte.com/scrivener/faqs/", es: "Preguntas: licencia, número de serie, actualizaciones", en: "FAQ: licence, serial number, updates" },
  "scr-kb-sync": { app: "scrivener", url: "https://scrivener.tenderapp.com/help/kb/cloud-syncing/using-scrivener-with-cloud-sync-services", es: "Ayuda: los proyectos se guardan en tu disco", en: "Help: projects are saved on your disk" },
  "scr-eula": { app: "scrivener", url: "https://www.literatureandlatte.com/wp-content/uploads/2023/09/Scrivener-EULA-Mac.pdf", es: "Licencia de uso (PDF)", en: "End-user licence (PDF)" },

  "dab-pricing": { app: "dabble", url: "https://www.dabblewriter.com/pricing", es: "Precios y planes, móvil, dónde guarda", en: "Pricing and plans, mobile, where it stores" },
  "dab-home": { app: "dabble", url: "https://www.dabblewriter.com/", es: "En cualquier dispositivo; copias", en: "On any device; backups" },
  "dab-ai": { app: "dabble", url: "https://www.dabblewriter.com/docs/reference/dabble-is-ai-free", es: "Sin IA, a propósito", en: "AI-free, by design" },
  "dab-versions": { app: "dabble", url: "https://www.dabblewriter.com/docs/managing-projects/version-history", es: "Ver y restaurar versiones", en: "View and restore versions" },
  "dab-offline": { app: "dabble", url: "https://www.dabblewriter.com/docs/apps-sync-offline/working-offline", es: "Sin conexión", en: "Working offline" },
  "dab-mobile": { app: "dabble", url: "https://www.dabblewriter.com/docs/apps-sync-offline/install-on-mobile", es: "En el móvil, como app web; cuenta", en: "On the phone, as a web app; account" },
  "dab-export": { app: "dabble", url: "https://www.dabblewriter.com/docs/import-export-printing/export-your-manuscript", es: "Exportar el manuscrito", en: "Export your manuscript" },
  "dab-terms": { app: "dabble", url: "https://www.dabblewriter.com/terms", es: "Términos: todos los derechos reservados", en: "Terms: all rights reserved" },

  "not-pricing": { app: "notion", url: "https://www.notion.com/pricing", es: "Precios, historial por plan, sin conexión", en: "Pricing, history by plan, offline" },
  "not-ai-faq": { app: "notion", url: "https://www.notion.com/help/notion-ai-faqs", es: "Notion AI: en qué planes", en: "Notion AI: which plans" },
  "not-history": { app: "notion", url: "https://www.notion.com/help/duplicate-delete-and-restore-content", es: "Historial de versiones y restaurar", en: "Version history and restore" },
  "not-residency": { app: "notion", url: "https://www.notion.com/help/data-residency", es: "Dónde guarda los datos", en: "Where data is stored" },
  "not-mobile": { app: "notion", url: "https://www.notion.com/mobile", es: "Apps para iOS y Android", en: "iOS and Android apps" },
  "not-export": { app: "notion", url: "https://www.notion.com/help/export-your-content", es: "Exportar", en: "Export" },
  "not-mcp": { app: "notion", url: "https://developers.notion.com/guides/mcp/overview", es: "Su servidor MCP, alojado en su nube", en: "Its MCP server, hosted in its cloud" },
  "not-terms": { app: "notion", url: "https://www.notion.so/notion/Personal-Use-Terms-of-Service-00e4e5d0f2b9411cbee6493f15779500", es: "Términos de uso personal", en: "Personal use terms" },

  "nc-pricing": { app: "novelcrafter", url: "https://www.novelcrafter.com/pricing", es: "Precios y planes (IA desde Hobbyist)", en: "Pricing and plans (AI from Hobbyist)" },
  "nc-claude": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/docs/ai-connections/claude", es: "Claude: solo vía OpenRouter", en: "Claude: only through OpenRouter" },
  "nc-ollama": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/docs/ai-connections/ollama", es: "Ollama, en tu equipo", en: "Ollama, on your computer" },
  "nc-lmstudio": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/docs/ai-connections/lm-studio", es: "LM Studio, en tu equipo", en: "LM Studio, on your computer" },
  "nc-offline": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/faq/general/can-i-use-nc-in-ofline-mode", es: "Solo con conexión", en: "Online only" },
  "nc-webapp": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/faq/general/web-app", es: "App web", en: "Web app" },
  "nc-history": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/docs/organization/revision-history", es: "Historial de revisiones", en: "Revision history" },
  "nc-export": { app: "novelcrafter", url: "https://www.novelcrafter.com/help/docs/export/novel", es: "Exportar", en: "Export" },
  "nc-terms": { app: "novelcrafter", url: "https://www.novelcrafter.com/terms-and-conditions", es: "Términos: su propiedad intelectual", en: "Terms: its intellectual property" },

  "sw-pricing": { app: "sudowrite", url: "https://sudowrite.com/pricing", es: "Precios (al año y mes a mes) y créditos", en: "Pricing (yearly and monthly) and credits" },
  "sw-mobile": { app: "sudowrite", url: "https://docs.sudowrite.com/resources/ktuxRrzphwp3uTNneRtaos/is-there-a-mobile-app/sFZPG2o8QqXR7bqrb9Swae", es: "App para iOS y Android", en: "iOS and Android app" },
  "sw-webapp": { app: "sudowrite", url: "https://docs.sudowrite.com/using-sudowrite/1ow1qkGqof9rtcyGnrWUBS/web-app-vs-mobile-app-differences/6JmxspPSKC83DkQZ7rFYcJ", es: "App web y app móvil; historial de documentos", en: "Web app and mobile app; document history" },
  "sw-export": { app: "sudowrite", url: "https://docs.sudowrite.com/using-sudowrite/1ow1qkGqof9rtcyGnrWUBS/exporting-files/3NtVWXcnwYaRCmPW2iwcCB", es: "Exportar", en: "Export" },
  "sw-terms": { app: "sudowrite", url: "https://sudowrite.com/terms-and-conditions", es: "Términos: cuenta y derechos", en: "Terms: account and rights" },

  "att-home": { app: "atticus", url: "https://www.atticus.io/", es: "Precio, sin conexión, nube, exportar; control de versiones «próximamente»", en: "Price, offline, cloud, export; version control “coming soon”" },
  "att-terms": { app: "atticus", url: "https://www.atticus.io/terms-conditions/", es: "Términos: su código", en: "Terms: its code" },
  "ree-write": { app: "reedsy", url: "https://reedsy.com/write-a-book", es: "Funciones, historial, cuenta; sin conexión «todavía no»", en: "Features, history, account; offline “not yet”" },
  "ree-pricing": { app: "reedsy", url: "https://reedsy.com/studio/pricing/", es: "Precios de los complementos", en: "Add-on pricing" },
  "ree-terms": { app: "reedsy", url: "https://reedsy.com/studio/terms", es: "Términos: su código", en: "Terms: its code" },
  "plo-pricing": { app: "plottr", url: "https://plottr.com/pricing/", es: "Precios de lista y de oferta, dónde guarda, sin conexión; con Pro, nube y colaboración; «No AI»", en: "List and sale prices, storage, offline; with Pro, cloud and collaboration; “No AI”" },
  "plo-features": { app: "plottr", url: "https://plottr.com/features/", es: "Funciones, exportar, apps", en: "Features, export, apps" },
  "plo-terms": { app: "plottr", url: "https://plottr.com/terms-conditions/", es: "Licencia de uso", en: "Licence terms" },
  "nw-home": { app: "novelwriter", url: "https://novelwriter.io/", es: "Qué es, dónde guarda, sistemas", en: "What it is, how it stores, systems" },
  "nw-repo": { app: "novelwriter", url: "https://github.com/saga-soft/novelWriter", es: "Código (GPL-3.0) y versión 2026.2.1", en: "Code (GPL-3.0) and release 2026.2.1" },
  "nw-build": { app: "novelwriter", url: "https://github.com/saga-soft/novelWriter/blob/main/docs/source/user_interface/manuscript.rst", es: "Documentación: formatos del manuscrito", en: "Docs: manuscript formats" },
  "nw-backup": { app: "novelwriter", url: "https://github.com/saga-soft/novelWriter/blob/main/docs/source/user_interface/projects.rst", es: "Documentación: copias al cerrar", en: "Docs: backups on close" },
  "mk-repo": { app: "manuskript", url: "https://github.com/olivierkes/manuskript", es: "Código (GPL-3.0), formatos y versión 0.17.0", en: "Code (GPL-3.0), formats and release 0.17.0" },
  "bib-home": { app: "bibisco", url: "https://bibisco.com/", es: "Qué es; sistemas; desde 2014; 15 idiomas", en: "What it is; systems; since 2014; 15 languages" },
  "bib-everywhere": { app: "bibisco", url: "https://bibisco.com/bibisco-everywhere/", es: "Everywhere: móvil y sincronización", en: "Everywhere: phone and sync" },
  "bib-repo": { app: "bibisco", url: "https://github.com/andreafeccomandi/bibisco", es: "Código (GPL-3.0), revisiones y exportar", en: "Code (GPL-3.0), revisions and export" },
  "yw-home": { app: "ywriter", url: "https://www.spacejock.com/yWriter.html", es: "Versiones y sistemas; el móvil, vía Dropbox", en: "Versions and systems; the phone, through Dropbox" },
  "yw-7": { app: "ywriter", url: "https://www.spacejock.com/yWriter7.html", es: "yWriter7: gratis en Windows", en: "yWriter7: free on Windows" },

  "nai-home": { app: "novelai", url: "https://novelai.net/", es: "Qué es", en: "What it is" },
  "nai-tiers": { app: "novelai", url: "https://docs.novelai.net/en/subscription/", es: "Planes y precios", en: "Tiers and prices" },
  "nai-faq": { app: "novelai", url: "https://docs.novelai.net/en/faq", es: "Preguntas: dónde guarda, conexión, móvil, exportar", en: "FAQ: storage, connection, phone, export" },
  "nai-terms": { app: "novelai", url: "https://novelai.net/terms", es: "Términos: su propiedad", en: "Terms: its ownership" },
  "sq-pricing": { app: "squibler", url: "https://www.squibler.io/pricing", es: "Precios, créditos y exportar", en: "Pricing, credits and export" },
  "sq-home": { app: "squibler", url: "https://www.squibler.io/", es: "Qué es", en: "What it is" },
  "sq-terms": { app: "squibler", url: "https://www.squibler.io/terms-and-conditions/", es: "Términos: cuenta y su código", en: "Terms: account and its code" },

  "gd-docs": { app: "googledocs", url: "https://workspace.google.com/intl/en/products/docs/", es: "Docs: en línea, sin conexión, móvil, cuenta", en: "Docs: online, offline, phone, account" },
  "gd-history": { app: "googledocs", url: "https://support.google.com/docs/answer/190843?hl=en", es: "Ayuda: restaurar una versión", en: "Help: restore an earlier version" },
  "gd-export": { app: "googledocs", url: "https://developers.google.com/workspace/drive/api/guides/ref-export-formats", es: "Formatos de exportación", en: "Export formats" },
  "gd-aipro": { app: "googledocs", url: "https://one.google.com/about/plans", es: "Google AI Pro (Gemini en Docs)", en: "Google AI Pro (Gemini in Docs)" },
  "gd-terms": { app: "googledocs", url: "https://policies.google.com/terms?hl=en", es: "Términos de Google", en: "Google’s terms" },
  "ms-plans": { app: "word", url: "https://www.microsoft.com/en-us/microsoft-365/buy/compare-all-microsoft-365-products", es: "Planes, precios y Copilot", en: "Plans, prices and Copilot" },
  "ms-terms": { app: "word", url: "https://www.microsoft.com/en-us/servicesagreement", es: "Contrato de servicios: el software", en: "Services Agreement: the software" },
  "obs-pricing": { app: "obsidian", url: "https://obsidian.md/pricing", es: "App gratis; Sync (con bóvedas compartidas) y Publish; sin registro", en: "Free app; Sync (with shared vaults) and Publish; no sign-up" },
  "obs-storage": { app: "obsidian", url: "https://obsidian.md/help/data-storage", es: "Notas en Markdown, en una carpeta tuya", en: "Notes in Markdown, in your own folder" },
  "obs-recovery": { app: "obsidian", url: "https://obsidian.md/help/plugins/file-recovery", es: "Recuperación de archivos", en: "File recovery" },
  "obs-sync-history": { app: "obsidian", url: "https://obsidian.md/help/sync/version-history", es: "Historial de Sync: 1 mes (Standard) o 12 (Plus)", en: "Sync’s version history: 1 month (Standard) or 12 (Plus)" },
  "obs-mobile": { app: "obsidian", url: "https://obsidian.md/mobile", es: "Apps para iOS y Android", en: "iOS and Android apps" },
  "obs-license": { app: "obsidian", url: "https://obsidian.md/license", es: "Licencia: su código", en: "Licence: its code" },
  "uly-pricing": { app: "ulysses", url: "https://ulysses.app/pricing/", es: "Precios", en: "Pricing" },
  "uly-home": { app: "ulysses", url: "https://ulysses.app/", es: "Funciones, iCloud, exportar", en: "Features, iCloud, export" },
  "ia-pricing": { app: "iawriter", url: "https://ia.net/writer/pricing", es: "Precios y sistemas", en: "Pricing and systems" },
  "ia-home": { app: "iawriter", url: "https://ia.net/writer", es: "Funciones y marca de autoría de IA", en: "Features and AI-authorship marking" },
  "ia-eula": { app: "iawriter", url: "https://ia.net/legal/eula", es: "Licencia de uso", en: "End-user licence" },

  "ne-repo": { app: "novelengine", url: "https://github.com/john-paul-ruf/novel-engine", es: "Código (AGPL-3.0), README y v0.9.4", en: "Code (AGPL-3.0), README and v0.9.4" },
  "ne-technical": { app: "novelengine", url: "https://github.com/john-paul-ruf/novel-engine/blob/main/TECHNICAL.md", es: "Detalles técnicos: historial", en: "Technical notes: history" },
  "sim-repo": { app: "siming", url: "https://github.com/teangtang1122/siming-ai", es: "Código (Apache-2.0), README y v3.5.0", en: "Code (Apache-2.0), README and v3.5.0" },
  "den-repo": { app: "denova", url: "https://github.com/alfredxw/denova", es: "Código (Apache-2.0), README y v0.5.1", en: "Code (Apache-2.0), README and v0.5.1" },
  "ow-repo": { app: "openwriter", url: "https://github.com/travsteward/openwriter", es: "Código (MIT), MCP y v0.42.0", en: "Code (MIT), MCP and v0.42.0" },
  "vela-repo": { app: "vela", url: "https://github.com/heider-x/vela", es: "Código (GPL-3.0) y v0.1.0", en: "Code (GPL-3.0) and v0.1.0" },
  "aq-repo": { app: "augmentedquill", url: "https://github.com/StableLlamaAI/AugmentedQuill", es: "Código (GPL-3.0) y v0.9.2", en: "Code (GPL-3.0) and v0.9.2" },
  "owr-repo": { app: "openwrite", url: "https://github.com/ilrein/openwrite", es: "Código (AGPL-3.0)", en: "Code (AGPL-3.0)" },
  "on-repo": { app: "opennovel", url: "https://github.com/Yaemikoreal/OpenNovel", es: "Código (MIT) y servidor MCP", en: "Code (MIT) and MCP server" },
  "smcp-repo": { app: "scrivenermcp", url: "https://github.com/writerslogic/scrivener-mcp", es: "Código (AGPL-3.0) y herramientas", en: "Code (AGPL-3.0) and tools" },
  "ana-repo": { app: "awesomenovelagent", url: "https://github.com/modoojunko/awesome-novel-agent", es: "Código, licencia y v4.28.0", en: "Code, licence and v4.28.0" },

  "claude-pricing": { app: "ai", url: "https://claude.com/pricing", es: "Claude Pro incluye Claude Code", en: "Claude Pro includes Claude Code" },
  "chatgpt-pricing": { app: "ai", url: "https://learn.chatgpt.com/docs/pricing", es: "Codex en los planes de ChatGPT, también Free", en: "Codex in ChatGPT plans, Free included" },
  "ollama-pricing": { app: "ai", url: "https://ollama.com/pricing", es: "Ollama en tu equipo: gratis y sin límite", en: "Ollama on your machine: free and unlimited" },
  "opencode": { app: "ai", url: "https://opencode.ai/", es: "OpenCode, con tu cuenta de ChatGPT o Copilot", en: "OpenCode, with your ChatGPT or Copilot account" },
  "grok-build": { app: "ai", url: "https://docs.x.ai/build/overview", es: "Grok Build", en: "Grok Build" },
};

const VS = ["vs-readme", "vs-details"];

/** Rows of the full page, in its groups; the landing shows the six with `landing`. */
export const APPS = [
  {
    id: "versorium", name: "Versorium", group: "us",
    landing: {
      // The series, not one release: true of 0.1.0 and of 0.1.1, which came out
      // hours later (Codex rewrites in the installed app from 0.1.1). The words
      // after the version are the hero pill's (compare-parity.mjs, rule 9).
      note: code("v0.1 · probada solo en macOS", "v0.1 · only tried on macOS", "vs-release", "vs-first"),
      three: { ...code("0 $", "$0", ...VS), calc: "0" }, threeNote: code("código abierto", "open source", "vs-readme"),
      lives: code("Tus archivos, en Markdown", "Your own files, in Markdown", "vs-formats"),
      history: code("Cada minuto, sin caducar; volver aún requiere git", "Every minute, no expiry; going back still needs git", "vs-details", "vs-todo"),
      ai: code("Apagada, local, o Claude Code, Codex u OpenCode", "Off, local, or Claude Code, Codex or OpenCode", ...VS), aiNote: code("con tu suscripción", "on your own subscription", "claude-pricing", "chatgpt-pricing"),
      account: code("Sin cuenta; funciona sin conexión", "No account; works offline", "vs-readme"),
      phone: code("No", "No", "vs-release"),
    },
    type: code("Escritorio · novela", "Desktop · novels"),
    price: code("Gratis", "Free", ...VS),
    three: { ...code("0 $", "$0", ...VS), calc: "0" },
    ai: code("Ninguna, un modelo dentro de la app, Ollama, o Claude Code, Codex u OpenCode con tu propia suscripción", "None, a model inside the app, Ollama, or Claude Code, Codex or OpenCode on your own subscription", ...VS),
    account: code("No", "No", "vs-readme"),
    lives: code("Archivos Markdown en una carpeta tuya", "Markdown files in a folder you own", "vs-formats"),
    history: code("Instantánea git cada minuto, antes de que la IA escriba y antes de borrar; registro de cada cambio; sin caducidad. Volver a una, por ahora, con git", "A git snapshot every minute, before AI writes and before a deletion; a log of every change; no expiry. Going back to one needs git, for now", "vs-details", "vs-todo"),
    offline: code("Sí", "Yes", "vs-readme"),
    phone: code("No", "No", "vs-release", "vs-readme"),
    open: code("Sí, AGPL-3.0", "Yes, AGPL-3.0", "vs-readme"),
    exports: code("Markdown, DOCX, EPUB 3, PDF, Scrivener", "Markdown, DOCX, EPUB 3, PDF, Scrivener", "vs-formats"),
  },

  // For writing novels
  {
    id: "scrivener", name: "Scrivener 3", group: "novel",
    landing: {
      three: calc("59,99 $", "$59.99", "59.99", "scr-store", ["Standard Licence for macOS", "US$5999"]),
      threeNote: y("pago único", "one-off", "scr-faq", "if you buy Scrivener 3, then all 3.x updates will be free"),
      lives: y("Un proyecto en tu disco", "A project on your disk", "scr-kb-sync", "Scrivener will save the files you change on your local hard drive"),
      history: y("Instantáneas y copias automáticas", "Snapshots and automatic backups", "scr-overview", ["take a “Snapshot” of a section", "automatically back up your projects whenever they are opened or closed"]),
      ai: ns(),
      account: y("Licencia; app de escritorio", "Licence; desktop app", ["scr-faq", "scr-store"], ["enter the serial number you were sent after purchase", "This is a download product."]),
      phone: y("iOS, 23,99 $ aparte", "iOS, $23.99 extra", "scr-store", ["Scrivener for iPad and iPhone.", "US$2399"]),
    },
    type: y("Escritorio · novela", "Desktop · novels", "scr-overview"),
    price: y("59,99 $ una vez por plataforma (macOS o Windows); las dos, 95,98 $; iOS, 23,99 $", "$59.99 once per platform (macOS or Windows); both, $95.98; iOS, $23.99", "scr-store", ["US$5999", "US$9598", "US$2399"]),
    three: calc("59,99 $", "$59.99", "59.99", "scr-store"),
    ai: ns(),
    account: y("Licencia con número de serie", "Licence with a serial number", "scr-faq", "enter the serial number you were sent after purchase"),
    lives: y("Un proyecto de Scrivener en tu disco", "A Scrivener project on your disk", "scr-kb-sync", "Scrivener will save the files you change on your local hard drive"),
    history: y("Instantáneas a las que puedes volver; copias automáticas al abrir y cerrar", "Snapshots you can return to; automatic backups on open and close", "scr-overview", ["you’ll be able to return to the earlier version whenever you want", "whenever they are opened or closed"]),
    offline: y("App de escritorio", "Desktop app", "scr-store", "This is a download product."),
    phone: y("iOS (23,99 $); sincroniza con Dropbox", "iOS ($23.99); syncs through Dropbox", "scr-store", "(Dropbox account required for sync features)"),
    open: no("No", "No", "scr-eula", "nor translate, adapt, modify, lease, rent, loan, redistribute, sub-lease, sub-license or create derivative works from the Software"),
    exports: y("Word, RTF, OpenOffice, Final Draft, PDF, EPUB", "Word, RTF, OpenOffice, Final Draft, PDF, EPUB", "scr-overview", ["Export to a wide variety of file formats, including Microsoft Word, RTF and OpenOffice", "Create ready-to-sell Epub ebooks"]),
  },
  {
    id: "dabble", name: "Dabble", group: "novel",
    landing: {
      three: calc("547,20 $", "$547.20", "19 * 12 * 0.8 * 3", "dab-pricing", ["$19/month", "Save 20% when you pay annually"]),
      lives: y("Tu ordenador y su nube", "Your computer and its cloud", "dab-pricing", "Dabble stores your work locally on your computer and syncs it to your secure Dabble account"),
      history: y("Versiones restaurables; copia en la nube", "Restorable versions and a cloud backup", ["dab-versions", "dab-pricing"], ["Restore this version", "Cloud backup and sync"]),
      ai: no("Ninguna, a propósito", "None, by design", "dab-ai", "Dabble will never put words on the page for you."),
      account: y("Cuenta; también sin conexión", "Account; offline too", ["dab-mobile", "dab-offline"], ["You need a Dabble account", "Dabble is offline-first"]),
      phone: y("iOS y Android", "iOS and Android", "dab-pricing", "Dabble works on iOS and Android"),
    },
    type: y("Web, escritorio y móvil · novela", "Web, desktop and phone · novels", "dab-home", "Your manuscript is waiting for you on every device — desktop, tablet, or phone."),
    price: y("19, 29 o 49 $ al mes; 20 % menos pagando al año; Author de por vida, 699 $", "$19, $29 or $49 a month; 20% off paid yearly; lifetime Author, $699", "dab-pricing", ["$19/month", "$29/month", "$49/month", "Save 20% when you pay annually", "Lifetime Author Access - $699"]),
    three: calc("547,20 $", "$547.20", "19 * 12 * 0.8 * 3", "dab-pricing"),
    ai: no("Ninguna, a propósito", "None, by design", "dab-ai", "Dabble will never put words on the page for you."),
    account: y("Sí", "Yes", "dab-mobile", "You need a Dabble account"),
    lives: y("Tu equipo y su nube, sincronizados", "Your device and its cloud, synced", "dab-pricing", "Dabble stores your work locally on your computer and syncs it to your secure Dabble account"),
    history: y("Versiones que se restauran, en los planes de pago; copias en la nube", "Versions you can restore, on paid plans; cloud backups", ["dab-versions", "dab-pricing"], ["Version history lives on Dabble’s paid plans.", "Restore this version", "Cloud backup and sync"]),
    offline: y("Sí, de entrada", "Yes, offline-first", "dab-offline", "Dabble is offline-first"),
    phone: y("iOS y Android, como app web", "iOS and Android, as a web app", ["dab-pricing", "dab-mobile"], ["Dabble works on iOS and Android", "Dabble’s mobile app is a web app."]),
    open: no("No", "No", "dab-terms", "ALL RIGHTS RESERVED"),
    exports: y("DOCX con formato de manuscrito, Google Docs, web y Markdown; PDF, imprimiendo", "Manuscript-format DOCX, Google Docs, web and Markdown; PDF by printing", "dab-export", "You can export your manuscript from Dabble to Word (.docx), Google Docs, the web, or Markdown. For a PDF, you use Print and save as PDF."),
  },
  {
    id: "atticus", name: "Atticus", group: "novel",
    type: y("Escritorio y web · escribir y maquetar", "Desktop and web · write and format", "att-home"),
    price: y("147 $ una vez", "$147 once", "att-home", "Price: $147"),
    three: calc("147 $", "$147", "147", "att-home"),
    ai: ns(),
    account: y("Sí", "Yes", "att-home", "You can also login to Atticus from any secure device"),
    lives: y("Guarda mientras escribes, con copia en su nube", "Saves as you write, backed up to its cloud", "att-home", "will back it up on the cloud"),
    history: no("Control de versiones «próximamente»", "Version control “coming soon”", "att-home", ["Version Control", "Coming Soon"]),
    offline: y("Sí", "Yes", "att-home", "Work online, offline, in a plane or on a train"),
    phone: y("En el navegador, también del móvil", "In the browser, phones included", "att-home", "including not just PCs and Macs, but also your tablets and even smartphones"),
    open: no("No", "No", "att-terms", "attempt to derive the source code of"),
    exports: y("EPUB, PDF, DOCX", "EPUB, PDF, DOCX", "att-home", "EPUB, PDF, DOCX"),
  },
  {
    id: "reedsy", name: "Reedsy Studio", group: "novel",
    type: y("Web · escribir y maquetar", "Web · write and format", "ree-write"),
    price: y("Gratis; Craft, 4,99 $ al mes; Outlining, 7,99 $ al mes", "Free; Craft, $4.99 a month; Outlining, $7.99 a month", "ree-pricing", ["$4.99/mo", "$7.99/mo", "the core features of Studio will remain free"]),
    three: calc("0 $", "$0", "0", "ree-pricing"),
    ai: ns(),
    account: y("Sí", "Yes", "ree-write", "Access Studio by creating a free Reedsy account."),
    lives: y("Su nube", "Its cloud", "ree-write", "Changes are automatically synced and backed up to the cloud as you write."),
    history: y("30 días gratis; sin límite con Craft", "30 days free; unlimited with Craft", "ree-write", ["30 days are included for free", "To unlocked unlimited history, you can upgrade to Craft."]),
    offline: no("Todavía no", "Not yet", "ree-write", "Not yet. As of right now, you can only access Studio through an online browser"),
    phone: ns(),
    open: no("No", "No", "ree-terms", "not reverse engineer, decompile, disassemble or otherwise attempt to obtain Reedsy's source code"),
    exports: y("EPUB y PDF maquetado", "EPUB and typeset PDF", "ree-write", "Typeset to PDF and EPUB"),
  },
  {
    id: "plottr", name: "Plottr", group: "novel",
    type: y("Escritorio · planificar la trama", "Desktop · plotting", "plo-features"),
    // List prices, struck through on the page: it showed sale prices on AS_OF.
    price: y("80 $ al año o 199 $ de por vida (en oferta: 60 y 150 $); Pro, 99 $ al año o 699 $ (en oferta: 599 $)", "$80 a year or $199 lifetime (on sale: $60 and $150); Pro, $99 a year or $699 (on sale: $599)", "plo-pricing", ["$80 $60/yr", "$199 $150", "$99/yr", "$699 $599"]),
    three: calc("199 $", "$199", "199", "plo-pricing", "$199 $150"),
    ai: no("Ninguna («No AI»)", "None (“No AI”)", "plo-pricing", "No AI"),
    account: ns(),
    lives: y("En tu equipo; con Pro, en su nube", "On your device; with Pro, in its cloud", "plo-pricing", ["On device", "In the Cloud"]),
    history: ns(),
    offline: y("Sí", "Yes", "plo-pricing", "Work Offline"),
    phone: y("Con Pro, sus apps web y móvil", "With Pro, its web and mobile apps", "plo-features", "when using our web, desktop, and mobile apps"),
    open: no("No", "No", "plo-terms", "Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the Application."),
    exports: y("Word, Scrivener", "Word, Scrivener", "plo-features", "Export to Microsoft Word & Scrivener"),
  },
  {
    id: "novelwriter", name: "novelWriter", group: "novel",
    type: y("Escritorio · novela · código abierto", "Desktop · novels · open source", "nw-home", "runs on Linux, Windows and MacOS"),
    price: y("Gratis", "Free", "nw-home", "novelWriter is Free and Open Source"),
    three: calc("0 $", "$0", "0", "nw-home"),
    ai: ns(),
    account: ns(),
    lives: y("Una carpeta de archivos de texto en tu disco", "A folder of plain text files on your disk", "nw-home", "many smaller plain text documents"),
    history: y("Copia zip automática al cerrar", "Automatic zip backup on close", "nw-backup", "Backups can run automatically when a project is closed"),
    offline: ns(),
    phone: ns(),
    open: y("Sí, GPL-3.0", "Yes, GPL-3.0", "nw-repo", "novelWriter is licenced under GPLv3"),
    exports: y("ODT, DOCX, PDF, HTML, EPUB, Markdown", "ODT, DOCX, PDF, HTML, EPUB, Markdown", "nw-build", ["Microsoft Word Document", "Electronic Publication E-book (EPub)", "Standard/Extended Markdown"]),
  },
  {
    id: "manuskript", name: "Manuskript", group: "novel",
    type: y("Escritorio · novela · código abierto", "Desktop · novels · open source", "mk-repo", "Manuskript runs on GNU/Linux, Mac OS X, and Windows."),
    price: y("Gratis", "Free", "mk-repo", "Manuskript is Free Software."),
    three: calc("0 $", "$0", "0", "mk-repo"),
    ai: ns(),
    account: ns(),
    lives: y("Archivos de texto abiertos, en tu disco", "Open, plain text files on your disk", "mk-repo", "automatic save in open and plain text file format"),
    history: ns(),
    offline: ns(),
    phone: ns(),
    open: y("Sí, GPL-3.0", "Yes, GPL-3.0", "mk-repo", "Manuskript is distributed under the GNU General Public License version 3"),
    exports: y("HTML, ePub, OpenDocument, DOCX y más", "HTML, ePub, OpenDocument, DOCX and more", "mk-repo", "Import and export document formats such as HTML, ePub, OpenDocument, DocX, and more"),
  },
  {
    id: "bibisco", name: "bibisco", group: "novel",
    type: y("Escritorio y móvil · novela · código abierto", "Desktop and phone · novels · open source", "bib-home", "available on Linux, macOS, Windows, Android and iOS"),
    price: y("Código abierto; Everywhere, aparte, con 14 días de prueba", "Open source; Everywhere, separately, with a 14-day trial", ["bib-repo", "bib-everywhere"], ["bibisco is an open source application for writing novels", "START YOUR 14-DAY FREE TRIAL"]),
    three: calc("0 $", "$0", "0", "bib-repo"),
    ai: ns(),
    account: ns(),
    lives: y("La app de escritorio; sincroniza con Everywhere", "The desktop app; syncs with Everywhere", "bib-everywhere", "Works with the bibisco desktop app on Linux, macOS, and Windows"),
    history: y("Gestiona revisiones", "Manages revisions", "bib-repo", "manage revisions"),
    offline: ns(),
    phone: y("Android, iPhone y iPad, con Everywhere", "Android, iPhone and iPad, with Everywhere", "bib-everywhere", "with the mobile app on Android, iPhone, and iPad"),
    open: y("Sí, GPL-3.0", "Yes, GPL-3.0", "bib-repo", "bibisco is an open source application for writing novels"),
    exports: y("PDF, DOCX, TXT", "PDF, DOCX, TXT", "bib-repo", "export novel in pdf, docx, or txt"),
  },
  {
    id: "ywriter", name: "yWriter", group: "novel",
    type: y("Escritorio y móvil · novela", "Desktop and phone · novels", "yw-home", ["yWriter7 for Windows", "yWriter for Android", "yWriter for IOS", "yWriter7 for MacOS"]),
    price: y("Gratis en Windows", "Free on Windows", "yw-7", "Best of all, yWriter is free (on Windows)."),
    three: calc("0 $", "$0", "0", "yw-7"),
    ai: ns(),
    account: ns(),
    lives: y("En tu equipo; en el móvil, vía Dropbox", "On your computer; on the phone, through Dropbox", "yw-home", "Mobile versions of yWriter are designed for editing your PC projects on the go, using Dropbox."),
    history: ns(),
    offline: ns(),
    phone: y("Android e iOS", "Android and iOS", "yw-home", ["yWriter for Android", "yWriter for IOS"]),
    open: ns(),
    exports: ns(),
  },

  // With paid AI
  {
    id: "sudowrite", name: "Sudowrite", group: "ai",
    landing: {
      three: calc("360 $", "$360", "10 * 12 * 3", "sw-pricing", ["$10", "Up to 50% off"]),
      lives: y("Su app web", "Its web app", "sw-webapp", "the full web app"),
      history: y("Historial de documentos", "Document history", "sw-webapp", "Document History and (Project and Document) Trash access"),
      ai: y("La suya, con créditos", "Its own, on credits", "sw-pricing", ["credits per month", "Sudowrite’s AI models just for fiction"]),
      account: y("Cuenta; —", "Account; —", "sw-terms", "If you create an account on the Website"),
      phone: y("iOS y Android", "iOS and Android", "sw-mobile", "Sudowrite has a mobile app available on both iOS and Android."),
    },
    type: y("Web y móvil · con IA", "Web and phone · AI", ["sw-webapp", "sw-mobile"]),
    price: y("10, 22 o 44 $ al mes pagando al año; 19, 29 o 59 $ mes a mes", "$10, $22 or $44 a month paid yearly; $19, $29 or $59 month to month", "sw-pricing", ["$10", "$22", "$44", "Up to 50% off"]),
    three: calc("360 $", "$360", "10 * 12 * 3", "sw-pricing"),
    ai: y("La suya y más de 30 modelos, por créditos (de 225.000 a 2.000.000 al mes)", "Its own and 30+ models, on credits (225,000 to 2,000,000 a month)", "sw-pricing", ["+30 industry-leading models", "225,000", "2,000,000"]),
    account: y("Sí", "Yes", "sw-terms", "If you create an account on the Website"),
    lives: y("Su app web", "Its web app", "sw-webapp", "the full web app"),
    history: y("Historial de documentos y papelera, en la app web", "Document history and a trash, in the web app", "sw-webapp", "Document History and (Project and Document) Trash access"),
    offline: ns(),
    phone: y("iOS y Android (app de apoyo)", "iOS and Android (a companion app)", "sw-mobile", "The mobile app is intended to be a companion app"),
    open: no("No", "No", "sw-terms", "all rights, titles, and interests in and to such property will remain (as between the parties) solely with the Operator"),
    exports: y("DOCX y ZIP; la Story Bible en CSV", "DOCX and ZIP; the Story Bible as CSV", "sw-export", ["Export (.docx)", "Export (.zip)", ".CSV file"]),
  },
  {
    id: "novelcrafter", name: "Novelcrafter", group: "ai",
    landing: {
      three: calc("120 $", "$120", "40 * 3", "nc-pricing", ["$4.00", "2 Months off"]),
      // The $120 plan (Scribe) has no AI; AI starts at Hobbyist, $80 a year.
      threeNote: calc("con IA, 240 $", "with AI, $240", "80 * 3", "nc-pricing", ["$8.00", "AI (Bring your own Key)", "2 Months off"]),
      lives: y("Su app web", "Its web app", "nc-webapp", "How can I use Novelcrafter as a web app?"),
      history: y("Revisiones restaurables", "Revisions you can restore", "nc-history", "Opening the Revision History allows you to restore any version at any time."),
      ai: y("Tu clave de API o modelos locales", "Your own API key or local models", ["nc-pricing", "nc-ollama", "nc-lmstudio"], ["AI (Bring your own Key)", "Connect to Ollama to run your AI models locally.", "Connect to LM Studio to run your AI models locally."]),
      account: no("Cuenta; solo con conexión", "Account; online only", ["nc-pricing", "nc-offline"], ["each user will need to have their own account and subscription", "Right now you can only use Novelcrafter with an active internet connection."]),
      phone: ns(),
    },
    type: y("Web · con IA (tu clave o local)", "Web · AI (your key or local)", ["nc-webapp", "nc-ollama"]),
    price: y("4, 8, 14 o 20 $ al mes; 40, 80, 140 o 200 $ al año", "$4, $8, $14 or $20 a month; $40, $80, $140 or $200 a year", "nc-pricing", ["$4.00", "$8.00", "$14.00", "$20.00", "2 Months off"]),
    three: calc("120 $", "$120", "40 * 3", "nc-pricing"),
    ai: y("Tu clave de API o modelos locales (Ollama, LM Studio), desde Hobbyist; Claude, solo vía OpenRouter", "Your own API key or local models (Ollama, LM Studio), from Hobbyist; Claude only through OpenRouter", ["nc-pricing", "nc-ollama", "nc-lmstudio", "nc-claude"], ["AI (Bring your own Key)", "Connect to Ollama to run your AI models locally.", "Connect to LM Studio to run your AI models locally.", "You will currently need to connect your API key via OpenRouter to use it within Novelcrafter."]),
    account: y("Sí", "Yes", "nc-pricing", "each user will need to have their own account and subscription"),
    lives: y("Su app web", "Its web app", "nc-webapp", "How can I use Novelcrafter as a web app?"),
    history: y("Revisiones que puedes restaurar", "Revisions you can restore", "nc-history", "Opening the Revision History allows you to restore any version at any time."),
    offline: no("No («solo con conexión»)", "No (“only with an active internet connection”)", "nc-offline", "Right now you can only use Novelcrafter with an active internet connection."),
    phone: ns(),
    open: no("No", "No", "nc-terms", "All content directly provided by Novelcrafter remains the intellectual property of Novelcrafter."),
    exports: y("DOCX y Markdown; a Scrivener y a Atticus", "DOCX and Markdown; to Scrivener and Atticus", "nc-export", ["Word (.docx)", "Export to Scrivener", "Export to Atticus"]),
  },
  {
    id: "novelai", name: "NovelAI", group: "ai",
    type: y("Web · con IA", "Web · AI", "nai-home", "STORY GENERATION"),
    price: y("10, 15 o 25 $ al mes", "$10, $15 or $25 a month", "nai-tiers", ["$10 USD monthly", "costing $15 USD", "$25 USD per month"]),
    three: calc("360 $", "$360", "10 * 12 * 3", "nai-tiers"),
    ai: y("La suya, por suscripción", "Its own, by subscription", "nai-tiers", "With a Tablet subscription, you can already use the Text and Voice generation AI"),
    account: y("Sí", "Yes", "nai-faq", "losing your email or password results in permanently losing access"),
    lives: y("Sus servidores, cifradas; o tu navegador", "Its servers, encrypted; or your browser", "nai-faq", ["By default, text stories are stored on our servers, but they are encrypted in your browser", "You also have the option to store your stories locally"]),
    history: ns(),
    offline: no("No («con una conexión estable»)", "No (“a stable internet connection”)", "nai-faq", "as long as you have a stable internet connection"),
    phone: y("En el navegador del móvil", "In the phone’s browser", "nai-faq", "You can already access NovelAI through your mobile web browser."),
    open: no("No", "No", "nai-terms", "Anlatan remains the sole owner of all right, title, and interest in the Services."),
    exports: y("Sus formatos .story y .scenario; texto", "Its .story and .scenario formats; plain text", "nai-faq", ["Letting you export your story as .story and .scenario files", "export the story as raw text"]),
  },
  {
    id: "squibler", name: "Squibler", group: "ai",
    type: y("Web · con IA", "Web · AI", "sq-home"),
    price: y("Gratis (1.000 créditos al mes); Plus, 29,99 $ al mes o 15,83 $ pagando al año; Pro, 89,99 $ o 49,17 $", "Free (1,000 credits a month); Plus, $29.99 a month or $15.83 paid yearly; Pro, $89.99 or $49.17", "sq-pricing", ["$0 forever", "1,000 AI credits/month", "$29.99 $15.83 /month", "$89.99 $49.17 /month"]),
    three: calc("0 $", "$0", "0", "sq-pricing"),
    ai: y("La suya, por créditos", "Its own, on credits", "sq-pricing", "AI credits/month"),
    account: y("Sí", "Yes", "sq-terms", "Account Registration and Security"),
    lives: ns(),
    history: ns(),
    offline: ns(),
    phone: ns(),
    open: no("No", "No", "sq-terms", "You may not copy, modify, reverse engineer, decompile, disassemble, or create derivative works based on any part of the Service or its underlying software."),
    exports: y("PDF y DOCX (Plus)", "PDF and DOCX (Plus)", "sq-pricing", "Export project to PDF and DOCX"),
  },

  // For writing in general
  {
    id: "notion", name: "Notion", group: "general",
    landing: {
      three: calc("0 $", "$0", "0", "not-pricing", ["Free", "$0"]),
      // Versorium's $0 is not alone: say whose plan this one is.
      threeNote: y("plan Free", "Free plan", "not-pricing", "Free"),
      lives: y("Su nube", "Its cloud", "not-residency", "Notion is hosted by AWS"),
      history: y("7 a 90 días; Enterprise, sin límite", "7 to 90 days; Enterprise, unlimited", "not-history", ["7 days if you're on a Free Plan.", "90 days if you're on a Business Plan.", "Any number of days if you're on an Enterprise Plan."]),
      ai: y("Notion AI, plan Business", "Notion AI, Business plan", "not-ai-faq", "Notion AI is available on Business and Enterprise Plans."),
      account: y("Cuenta; páginas descargadas", "Account; pages you download", "not-pricing", ["Sign up", "Choose pages to download for offline use."]),
      phone: y("iOS y Android", "iOS and Android", "not-mobile", "Available on iOS and Android."),
    },
    type: y("Web, escritorio y móvil · notas y documentos", "Web, desktop and phone · notes and docs", ["not-pricing", "not-mobile"]),
    price: y("Free, 0 $; Plus, 10 $, y Business, 20 $, al mes por miembro pagando al año", "Free, $0; Plus, $10, and Business, $20, a member a month, paid yearly", "not-pricing", ["$0", "$10", "$20", "per member / month", "Save up to 20% with yearly"]),
    three: calc("0 $", "$0", "0", "not-pricing"),
    ai: y("Notion AI en Business y Enterprise; en Free y Plus, unas respuestas de prueba", "Notion AI on Business and Enterprise; on Free and Plus, a few trial responses", "not-ai-faq", ["Notion AI is available on Business and Enterprise Plans.", "Users on the Free and Plus Plans get a limited number of complimentary AI responses"]),
    account: y("Sí", "Yes", "not-pricing", "Sign up"),
    lives: y("Su nube (AWS; en EE. UU. por defecto)", "Its cloud (AWS; in the US by default)", "not-residency", ["Notion is hosted by AWS", "By default, your data will continue to reside in the United States."]),
    history: y("Una versión cada 10 minutos; 7, 30 o 90 días según el plan, sin límite en Enterprise; restaurable", "A version every 10 minutes; 7, 30 or 90 days by plan, unlimited on Enterprise; restorable", ["not-history", "not-pricing"], ["A new version of a particular page will be recorded every 10 minutes as you actively edit it.", "Any number of days if you're on an Enterprise Plan."]),
    offline: y("Las páginas que descargues", "Pages you download", "not-pricing", "Choose pages to download for offline use."),
    phone: y("iOS y Android", "iOS and Android", "not-mobile", "Available on iOS and Android."),
    open: no("No", "No", "not-terms", "Notion and its licensors exclusively own all right, title and interest in and to the Service"),
    exports: y("PDF, HTML, Markdown y CSV", "PDF, HTML, Markdown and CSV", "not-export"),
  },
  {
    id: "googledocs", name: "Google Docs", group: "general",
    type: y("Web y móvil · documentos", "Web and phone · documents", "gd-docs", "Online, collaborative documents"),
    price: y("Gratis con una cuenta de Google", "Free with a Google Account", "gd-docs", "Anyone with a Google Account can create in Docs."),
    three: calc("0 $", "$0", "0", "gd-docs"),
    ai: y("Gemini, con Google AI Pro (19,99 $ al mes)", "Gemini, with Google AI Pro ($19.99 a month)", "gd-aipro", ["Google AI Pro", "$19.99/mo", "Gemini in Gmail, Docs"]),
    account: y("Sí (cuenta de Google)", "Yes (a Google Account)", "gd-docs", "Anyone with a Google Account can create in Docs."),
    lives: y("En línea", "Online", "gd-docs", "Online, collaborative documents"),
    history: y("Historial de versiones restaurable", "Version history you can restore", "gd-history", "Restore an earlier version"),
    offline: y("Sí", "Yes", "gd-docs", "Stay productive, even offline"),
    phone: y("iOS y Android", "iOS and Android", "gd-docs", "available in the App Store and Play Store"),
    open: no("No", "No", "gd-terms", "You may not copy, modify, distribute, sell, or lease any part of our services or software"),
    exports: y("DOCX, ODT, RTF, PDF, TXT, HTML, EPUB, Markdown", "DOCX, ODT, RTF, PDF, TXT, HTML, EPUB, Markdown", "gd-export", [".docx", ".epub", ".md"]),
  },
  {
    id: "word", name: "Microsoft Word", group: "general",
    type: y("Escritorio, web y móvil · documentos", "Desktop, web and phone · documents", "ms-plans", "Use on PCs, Macs, phones & tablets"),
    price: y("Microsoft 365 Personal, 9,99 $ al mes o 99,99 $ al año; Office Home 2024, 179,99 $ una vez", "Microsoft 365 Personal, $9.99 a month or $99.99 a year; Office Home 2024, $179.99 once", "ms-plans", ["$99.99/year", "Or buy at $9.99/month", "$179.99", "One-time purchase for PC or Mac"]),
    three: calc("179,99 $", "$179.99", "179.99", "ms-plans"),
    ai: y("Copilot, en los planes de Microsoft 365", "Copilot, in the Microsoft 365 plans", "ms-plans", "desktop apps with Microsoft Copilot"),
    account: y("Cuenta de Microsoft, para Microsoft 365", "A Microsoft account, for Microsoft 365", "ms-plans", "What is a Microsoft account and why do I need it for Microsoft 365?"),
    lives: y("Tus archivos u OneDrive", "Your files or OneDrive", "ms-plans", ["desktop versions of apps like Word", "OneDrive"]),
    history: ns(),
    offline: y("App de escritorio", "Desktop app", "ms-plans", "desktop versions of apps like Word"),
    phone: y("Teléfonos y tabletas, con Microsoft 365", "Phones and tablets, with Microsoft 365", "ms-plans", "Use on PCs, Macs, phones & tablets"),
    open: no("No", "No", "ms-terms", "The software is licensed, not sold, and Microsoft reserves all rights to the software not expressly granted by Microsoft"),
    exports: ns(),
  },
  {
    id: "obsidian", name: "Obsidian", group: "general",
    type: y("Escritorio y móvil · notas en Markdown", "Desktop and phone · Markdown notes", ["obs-storage", "obs-mobile"]),
    price: y("App gratis; Sync, desde 4 $ al mes; Publish, desde 8 $ al mes", "Free app; Sync from $4 a month; Publish from $8 a month", "obs-pricing", ["$4", "$8", "billed annually"]),
    three: calc("0 $", "$0", "0", "obs-pricing"),
    ai: ns(),
    account: no("No («sin registro»)", "No (“no sign-up required”)", "obs-pricing", "No sign-up required."),
    lives: y("Una carpeta de archivos Markdown en tu equipo", "A folder of Markdown files on your device", "obs-storage", "Obsidian stores your notes as Markdown-formatted plain text files in a vault. A vault is a folder on your local file system"),
    history: y("Recuperación de archivos en tu equipo, 7 días por defecto; con Sync, 1 mes (Standard) o 12 meses (Plus)", "File recovery on your device, 7 days by default; with Sync, 1 month (Standard) or 12 months (Plus)", ["obs-recovery", "obs-sync-history"], ["kept for 7 days", "On the Standard plan, notes are retained for 1 month, while on the Plus plan, they are kept for 12 months."]),
    offline: y("Sí", "Yes", "obs-pricing", "your data is stored locally on your device"),
    phone: y("iOS y Android", "iOS and Android", "obs-mobile", "Available for free on iOS and Android."),
    open: no("No", "No", "obs-license", "We own and reserve rights to our content, including text, images, and code in the app"),
    exports: ns(),
  },
  {
    id: "ulysses", name: "Ulysses", group: "general",
    type: y("Mac, iPhone y iPad · escritura", "Mac, iPhone and iPad · writing", "uly-home", "The Ultimate Writing App for Mac, iPad and iPhone"),
    price: y("39,99 $ al año o 5,99 $ al mes (precios de EE. UU.)", "$39.99 a year or $5.99 a month (US prices)", "uly-pricing", ["$39.99 per Year", "Or $5.99 per Month", "Prices apply to the U.S."]),
    three: calc("119,97 $", "$119.97", "39.99 * 3", "uly-pricing"),
    ai: ns(),
    account: y("Se compra en la App Store", "Bought in the App Store", "uly-home", "Download Ulysses from the App Store"),
    lives: y("Su biblioteca, sincronizada con iCloud", "Its library, synced through iCloud", ["uly-home", "uly-pricing"], ["All your texts will be stored in Ulysses’ library", "Full, seamless iCloud synchronization"]),
    history: ns(),
    offline: ns(),
    phone: y("iPhone y iPad", "iPhone and iPad", "uly-home", "The Ultimate Writing App for Mac, iPad and iPhone"),
    open: ns(),
    exports: y("PDF, Word, libros electrónicos y blogs", "PDF, Word, ebooks and blogs", "uly-home", "Ulysses can turn your texts into beautiful PDFs, Word documents, ebooks and even blog posts"),
  },
  {
    id: "iawriter", name: "iA Writer", group: "general",
    type: y("Escritorio y móvil · escritura en Markdown", "Desktop and phone · Markdown writing", "ia-home"),
    price: y("Una vez: Mac 49,99 $, Windows 39,99 $, iPhone y iPad 49,99 $; Android, suscripción", "Once: Mac $49.99, Windows $39.99, iPhone and iPad $49.99; Android, a subscription", "ia-pricing", ["One-Time Payment", "$49.99", "$39.99", "Android subscriptions"]),
    three: calc("39,99–49,99 $", "$39.99–49.99", "39.99 – 49.99", "ia-pricing"),
    ai: y("Marca el texto escrito por IA", "Marks text written by AI", "ia-home", "AI stands out in color."),
    account: ns(),
    lives: y("Archivos de texto en Markdown", "Plain text files in Markdown", "ia-home", "Write in plain text with Markdown."),
    history: ns(),
    offline: ns(),
    phone: y("iOS y Android", "iOS and Android", "ia-pricing", ["iPhone & iPad", "Android"]),
    open: no("No", "No", "ia-eula", "attempt to derive the source code of, modify, or create derivative works of the Apps"),
    exports: y("PDF, Word, HTML", "PDF, Word, HTML", "ia-home", "you can copy as HTML, or export it to PDF or Word"),
  },

  // Open source, with AI or agents
  {
    id: "novelengine", name: "Novel Engine", group: "open",
    type: y("Escritorio · novela con agentes de IA · código abierto", "Desktop · novels with AI agents · open source", "ne-repo", "Seven AI agents handle the editorial pipeline"),
    price: y("Gratis", "Free", "ne-repo", "Open source. Free."),
    three: calc("0 $", "$0", "0", "ne-repo"),
    ai: y("Claude Code con tu suscripción, Codex CLI, Ollama, llama-server", "Claude Code on your subscription, Codex CLI, Ollama, llama-server", "ne-repo", ["Novel Engine drives the same Claude Code CLI your subscription already covers", "Codex CLI", "llama-server"]),
    account: no("No («sin cuentas»)", "No (“no accounts”)", "ne-repo", "Novel Engine has no cloud, no accounts, and no telemetry."),
    lives: y("Archivos Markdown en tu disco", "Markdown files on your disk", "ne-repo", "As plain Markdown files in a folder on your computer"),
    history: y("Cada cambio en instantánea, hasta 50 versiones por archivo; restaurar en un clic", "Every change snapshotted, up to 50 versions per file; one-click restore", ["ne-repo", "ne-technical"], ["every change to every file is snapshotted", "restore with one click", "pruned to 50 versions per file per book"]),
    offline: y("Con Ollama", "With Ollama", "ne-repo", "with Ollama, the entire pipeline runs on your machine with no internet at all"),
    phone: ns(),
    open: y("Sí, AGPL-3.0", "Yes, AGPL-3.0", "ne-repo", "The application code is licensed under AGPL-3.0-only."),
    exports: y("Markdown, DOCX, EPUB (con Pandoc)", "Markdown, DOCX, EPUB (with Pandoc)", "ne-repo", "Your manuscript compiled to Markdown, DOCX, and EPUB"),
  },
  {
    id: "siming", name: "Siming (司命)", group: "open",
    type: y("Escritorio (Windows) y Android · novela con IA · código abierto", "Desktop (Windows) and Android · novels with AI · open source", "sim-repo", ["下载 Windows 安装版", "Android 8+"]),
    price: y("Gratis", "Free", "sim-repo", "软件本身永久免费、源码公开"),
    three: calc("0 $", "$0", "0", "sim-repo"),
    ai: y("Claude Code, Codex, OpenCode o DeepSeek Harness en tu equipo, APIs, o modelos locales con llama.cpp", "Claude Code, Codex, OpenCode or DeepSeek Harness on your computer, APIs, or local models with llama.cpp", "sim-repo", "也可以调用 Claude Code、Codex、OpenCode、DeepSeek Harness（DSH）等本机 CLI，或使用 llama.cpp 运行本地 GGUF"),
    account: ns(),
    lives: y("Una base de datos en tu equipo, con copia en Markdown", "A database on your computer, mirrored as Markdown", "sim-repo", ["数据库是权威写入源，Markdown/JSON 文件作为可阅读镜像", "保存在你选择的本机目录"]),
    history: y("Una instantánea antes y después de escribir cada capítulo; diferencias y restaurar", "A snapshot before and after each chapter is written; diffs and restore", "sim-repo", "每次写章前后保留快照；对新章不满意时，可查看差异并恢复旧版"),
    offline: y("En Android, una copia que se edita sin conexión", "On Android, a copy you can edit offline", "sim-repo", "Android 保留可写离线副本"),
    phone: y("Android", "Android", "sim-repo", "Android 8+"),
    open: y("Sí, Apache-2.0", "Yes, Apache-2.0", "sim-repo", "项目采用 Apache 2.0 许可证"),
    exports: y("TXT, Word y PDF", "TXT, Word and PDF", "sim-repo", "TXT/Word/PDF 导出"),
  },
  {
    id: "denova", name: "Denova", group: "open",
    type: y("Escritorio (Windows, macOS, Linux) · novela y rol con IA · código abierto", "Desktop (Windows, macOS, Linux) · novels and role-play with AI · open source", "den-repo", "Windows / macOS / Linux"),
    price: y("Código abierto", "Open source", "den-repo", "Apache-2.0"),
    three: calc("0 $", "$0", "0", "den-repo"),
    ai: y("Sus agentes, Codex o Claude Code; se configura con tu clave de API", "Its own agents, Codex or Claude Code; set up with your API key", "den-repo", ["支持 Native、Codex 和 Claude Code", "按启动引导添加语言模型的 API Key 和模型名"]),
    account: ns(),
    lives: y("Documentos Markdown en la carpeta del proyecto", "Markdown documents in the project folder", "den-repo", ["Markdown 文档", "直接打开已有项目目录"]),
    history: y("Versiones locales; diferencias y restaurar", "Local versions; diffs and restore", "den-repo", "保存本地版本、查看差异、恢复历史文件"),
    offline: ns(),
    phone: y("En la pantalla de inicio del móvil", "On the phone’s home screen", "den-repo", "添加到手机主屏幕"),
    open: y("Sí, Apache-2.0", "Yes, Apache-2.0", "den-repo", "Apache-2.0"),
    exports: ns(),
  },
  {
    id: "openwriter", name: "OpenWriter", group: "open",
    type: y("En el navegador, en local · escribir con agentes por MCP · código abierto", "In the browser, locally · writing with agents over MCP · open source", "ow-repo", "opens it at localhost:5050"),
    price: y("Código abierto", "Open source", "ow-repo", "MIT, by Travis Steward"),
    three: calc("0 $", "$0", "0", "ow-repo"),
    ai: y("La de tu agente, por MCP (24 herramientas)", "Your agent’s, over MCP (24 tools)", "ow-repo", ["OpenWriter ships no agent of its own.", "24 tools to read, write, and organize documents"]),
    account: ns(),
    lives: y("Archivos .md en tu disco", ".md files on your disk", "ow-repo", "Documents are plain .md files on disk"),
    history: y("Instantáneas con vuelta atrás; envía a GitHub", "Snapshots with rollback; pushes to GitHub", "ow-repo", ["Automatic snapshots with full rollback.", "Push documents to GitHub straight from the editor."]),
    offline: ns(),
    phone: ns(),
    open: y("Sí, MIT", "Yes, MIT", "ow-repo", "MIT, by Travis Steward"),
    exports: y("Markdown, HTML, Word, texto y PDF", "Markdown, HTML, Word, plain text and PDF", "ow-repo", "Export: Markdown, HTML, Word, plain text, and PDF."),
  },
  {
    id: "vela", name: "Vela", group: "open",
    type: y("Escritorio · escribir con IA · código abierto", "Desktop · writing with AI · open source", "vela-repo", "AI-powered IDE for novel writing"),
    price: y("Código abierto", "Open source", "vela-repo", "本项目采用 GPL-3.0 License 开源"),
    three: calc("0 $", "$0", "0", "vela-repo"),
    ai: y("Tu clave de API y Ollama; se conecta a servidores MCP", "Your own API key and Ollama; connects to MCP servers", "vela-repo", ["自带模型 BYOK (Bring Your Own Key)", "Ollama", "原生集成 MCP 协议"]),
    account: ns(),
    lives: y("Una base SQLite en tu equipo", "A SQLite database on your computer", "vela-repo", "内置 SQLite + 轻量向量引擎，所有数据存储在您的本地计算机"),
    history: ns(),
    offline: y("Sí", "Yes", "vela-repo", "断网依然可用"),
    phone: ns(),
    open: y("Sí, GPL-3.0", "Yes, GPL-3.0", "vela-repo", "本项目采用 GPL-3.0 License 开源"),
    exports: ns(),
  },
  {
    id: "augmentedquill", name: "AugmentedQuill", group: "open",
    type: y("Web en tu equipo · escribir con IA · código abierto", "Local web app · writing with AI · open source", "aq-repo", ["Web GUI for LLM assisted prose writing", "Runs on your machine"]),
    price: y("Gratis", "Free", "aq-repo", "Open source & free"),
    three: calc("0 $", "$0", "0", "aq-repo"),
    ai: y("llama.cpp u Ollama en tu equipo, o APIs en la nube", "llama.cpp or Ollama on your machine, or cloud APIs", "aq-repo", "connect a local LLM (llama.cpp/Ollama)"),
    account: no("No", "No", "aq-repo", "There is no subscription, account, or usage fee."),
    lives: y("Carpetas en tu equipo", "Folders on your computer", "aq-repo", "Your projects, chapters, and Sourcebook stay in local folders on your own machine."),
    history: ns(),
    offline: ns(),
    phone: ns(),
    open: y("Sí, GPL-3.0", "Yes, GPL-3.0", "aq-repo", "AugmentedQuill is open source (GPLv3)."),
    exports: ns(),
  },
  {
    id: "openwrite", name: "OpenWrite", group: "open",
    type: y("Web, alojada o en tu servidor · escribir con IA · código abierto", "Web, hosted or self-hosted · writing with AI · open source", "owr-repo", "Your manuscript lives in your database (or ours, or one you self-host)."),
    price: no("Sin suscripción; código abierto", "No subscription; open source", "owr-repo", "No subscription, no markup on tokens, no lock-in."),
    three: calc("0 $", "$0", "0", "owr-repo"),
    ai: y("Tu clave de API, Ollama incluido", "Your own API key, Ollama included", "owr-repo", ["an AI assistant that runs on your own API keys", "Ollama (fully local models, fully private)"]),
    account: y("Sí (correo y contraseña)", "Yes (email and password)", "owr-repo", "email/password accounts with personal workspaces"),
    lives: y("Una base de datos (D1/SQLite)", "A database (D1/SQLite)", "owr-repo", "D1 (SQLite)"),
    history: ns(),
    offline: ns(),
    phone: ns(),
    open: y("Sí, AGPL-3.0", "Yes, AGPL-3.0", "owr-repo", "AGPL-3.0 licensed"),
    exports: y("Markdown (DOCX y EPUB, «previstos»)", "Markdown (DOCX and EPUB “planned”)", "owr-repo", ["Markdown export", "Manuscript export (DOCX / EPUB)", "Planned"]),
  },
  {
    id: "opennovel", name: "OpenNovel", group: "open",
    type: y("Terminal · novela con agentes · código abierto", "Terminal · novels with agents · open source", "on-repo", "Local-first long-form novel operating system."),
    price: y("Código abierto", "Open source", "on-repo", "MIT license"),
    three: calc("0 $", "$0", "0", "on-repo"),
    ai: y("Claves de API vía LiteLLM; servidor MCP de 4 herramientas", "API keys through LiteLLM; a 4-tool MCP server", "on-repo", ["LiteLLM integration supports any provider", "Four tools exposed via Model Context Protocol"]),
    account: ns(),
    lives: y("Markdown y un registro SQLite", "Markdown and a SQLite ledger", "on-repo", ["Pure Markdown files", "SQLite event ledger"]),
    history: y("Instantáneas; cambios con diferencias y vuelta atrás", "Snapshots; changes with diffs and rollback", "on-repo", ["file-level snapshots", "Every state change goes through novel commit with diff review. Full rollback support."]),
    offline: ns(),
    phone: ns(),
    open: y("Sí, MIT", "Yes, MIT", "on-repo", "MIT license"),
    exports: ns(),
  },
  {
    id: "scrivenermcp", name: "scrivener-mcp", group: "open",
    type: y("Servidor MCP para Scrivener · código abierto", "MCP server for Scrivener · open source", "smcp-repo", "The definitive MCP server for Scrivener"),
    price: y("Código abierto (hace falta Scrivener)", "Open source (needs Scrivener)", "smcp-repo", "AGPL-3.0 license"),
    three: calc("59,99 $", "$59.99", "59.99", ["smcp-repo", "scr-store"]),
    ai: y("La de tu cliente MCP; algunas herramientas piden tu clave de API", "Your MCP client’s; some tools need your API key", "smcp-repo", ["connect your novels, screenplays, and manuscripts to Claude, ChatGPT, and any AI assistant", "Writing analysis, generation, enhancement, and semantic search need one"]),
    account: ns(),
    lives: y("Tu proyecto de Scrivener", "Your Scrivener project", "smcp-repo", "Opens the .scriv project"),
    history: ns(),
    offline: ns(),
    phone: ns(),
    open: y("Sí, AGPL-3.0", "Yes, AGPL-3.0", "smcp-repo", "AGPL-3.0 license"),
    exports: ns(),
  },
  {
    id: "awesomenovelagent", name: "awesome-novel-agent", group: "open",
    type: y("Habilidades para agentes de terminal", "Skills for terminal agents", "ana-repo"),
    price: y("Gratis para uso personal; uso comercial, con licencia", "Free for personal use; commercial use needs a licence", "ana-repo", ["个人使用免费", "商业使用 — 请联系作者获取授权"]),
    three: calc("0 $", "$0", "0", "ana-repo"),
    ai: y("Dentro de Claude Code, OpenCode, Codex, Grok Build y otros", "Inside Claude Code, OpenCode, Codex, Grok Build and others", "ana-repo", "支持 Claude Code / OpenCode / Reasonix / Codex / ZCode / DeepSeek Harness / Grok Build"),
    account: ns(),
    lives: y("La carpeta del proyecto", "The project folder", "ana-repo", "<小说项目路径>"),
    history: ns(),
    offline: ns(),
    phone: ns(),
    open: y("AGPL-3.0; uso comercial, con licencia", "AGPL-3.0; commercial use needs a licence", "ana-repo", ["AGPL-3.0", "商业使用 — 请联系作者获取授权"]),
    exports: ns(),
  },
];

/** The landing's columns, in order: Versorium, then the five alternatives alphabetically. */
export const LANDING = ["versorium", "dabble", "notion", "novelcrafter", "scrivener", "sudowrite"];
/** The landing's rows, in order (each app's `landing[row]`, plus the second lines). */
export const LANDING_ROWS = ["three", "lives", "history", "ai", "account", "phone"];
/** The full page's two tables. */
export const TABLE_A = ["price", "three", "ai", "account"];
export const TABLE_B = ["lives", "history", "offline", "phone", "open", "exports"];

export const GROUPS = {
  us: { es: "Versorium", en: "Versorium" },
  novel: { es: "Para escribir novelas", en: "For writing novels" },
  ai: { es: "Con IA de pago", en: "With paid AI" },
  general: { es: "Para escribir en general", en: "For writing in general" },
  open: { es: "Código abierto, con IA o agentes", en: "Open source, with AI or agents" },
};

/** The founding question (Grok, 2026-09-11), re-checked on AS_OF: what each of
    the closest tools brings together. Each cell from the tool's own page or
    repository (the same sources as its row); `ns` renders as a dash. */
const f = (es, en, quote) => ({ es, en, s: "y", ...(quote ? { quote: list(quote) } : {}) });
export const FOUNDING = {
  columns: {
    sub: { es: "Usa tu suscripción de IA", en: "Uses your AI subscription" },
    local: { es: "Modelos en tu equipo", en: "Models on your computer" },
    mcp: { es: "Su propio MCP", en: "Its own MCP" },
    desk: { es: "Un escritorio para la novela", en: "A desk for the novel" },
    history: { es: "Historial", en: "History" },
  },
  rows: [
    { id: "versorium", sub: f("Sí: Claude Code, Codex, OpenCode", "Yes: Claude Code, Codex, OpenCode"), local: f("Sí: integrado y Ollama", "Yes: built in, and Ollama"), mcp: f("Sí: solo lee hasta que lo permitas", "Yes: read-only until you allow writing"), desk: f("Sí", "Yes"), history: f("Git cada minuto y cada cambio", "Git every minute, and every change") },
    { id: "novelengine", sub: f("Sí: Claude Code, Codex", "Yes: Claude Code, Codex"), local: f("Sí: Ollama, llama-server", "Yes: Ollama, llama-server"), mcp: ns(), desk: f("Siete agentes, de la idea al libro", "Seven agents, from pitch to book", "Seven AI agents handle the editorial pipeline"), history: f("Instantáneas, hasta 50 por archivo", "Snapshots, up to 50 per file") },
    { id: "siming", sub: f("Sí: Claude Code, Codex, OpenCode", "Yes: Claude Code, Codex, OpenCode"), local: f("Sí: llama.cpp", "Yes: llama.cpp"), mcp: f("Sí", "Yes", "通过 MCP 读取项目上下文"), desk: f("Sí, en Windows y Android", "Yes, on Windows and Android"), history: f("Instantáneas antes y después de cada capítulo", "Snapshots before and after each chapter") },
    { id: "denova", sub: f("Sí: Codex, Claude Code", "Yes: Codex, Claude Code"), local: ns(), mcp: ns(), desk: f("Sí, para novela y rol", "Yes, for novels and role-play"), history: f("Versiones locales", "Local versions") },
    { id: "openwriter", sub: f("Tu agente la maneja por MCP", "Your agent drives it over MCP"), local: ns(), mcp: f("Sí: 24 herramientas", "Yes: 24 tools"), desk: ns(), history: f("Instantáneas; envía a GitHub", "Snapshots; pushes to GitHub") },
    { id: "scrivenermcp", sub: f("Tu cliente MCP", "Your MCP client"), local: ns(), mcp: f("Sí, para Scrivener", "Yes, for Scrivener"), desk: f("Scrivener", "Scrivener"), history: f("Las instantáneas de Scrivener", "Scrivener’s snapshots") },
    { id: "awesomenovelagent", sub: f("Corre dentro de Claude Code, Codex, OpenCode o Grok Build", "Runs inside Claude Code, Codex, OpenCode or Grok Build"), local: ns(), mcp: ns(), desk: ns(), history: ns() },
    { id: "opennovel", sub: f("Claves de API (LiteLLM)", "API keys (LiteLLM)"), local: f("Sí, vía LiteLLM", "Yes, through LiteLLM"), mcp: f("Sí: 4 herramientas", "Yes: 4 tools"), desk: f("En la terminal", "In the terminal"), history: f("Diferencias y vuelta atrás", "Diffs and rollback") },
    { id: "novelcrafter", sub: { es: "No con Claude Pro, según su web", en: "Not with Claude Pro, according to its website", s: "n", src: ["nc-claude"], quote: ["Having a Claude Pro subscription is not the same as an Anthropic API key."] }, local: f("Sí: Ollama, LM Studio", "Yes: Ollama, LM Studio", "One way to run AI interactions on your own hardware/computer/infrastructure is via Ollama."), mcp: ns(), desk: f("Sí, en la web", "Yes, on the web"), history: f("Revisiones que se restauran", "Revisions you can restore") },
  ],
};
